name: Deploy EcoFinds

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --production
      
    - name: Health check
      run: |
        npm start &
        sleep 5
        curl -f http://localhost:3000/api/health || exit 1
